### PR TITLE
Add a LICENSE file.

### PR DESCRIPTION
**Pull request by phst**
This puts the license in a central, easy to find spot.

### CODE REVIEW

**Comment by snarfed** [comment]
thanks for the PR!

sorry to say it, but [as mentioned](https://github.com/snarfed/fillcode/issues/3#issuecomment-261800589), i don't see a clear need for a separate LICENSE file. i get that it's common, and github shows a nice badge, but the README is tiny and the license declaration is very obvious there.

(also, public domain is the preferred license, so if we did add the file, it'd need to say that.)

let me know if you have a concrete use case for the separate file that isn't handled by the README declaration. thanks again for filing the issues and starting to contribute!

**Comment by phst** [comment]
Unfortunately I can't contribute patches unless the repository has a LICENSE file (corporate policy), a link to a license isn't enough.
It would be OK to append some public domain statement to the license though, as long is it remains clear that the repository can also be licensed under the Apache license.

**Comment by snarfed** [comment]
aha! thanks for the explanation. that corporate policy is indeed a reason to add the LICENSE file.

mind adding a public domain clause to the beginning, above the Apache license contents? this would be fine:

> This project is placed in the public domain. Alternatively, you may use it under the Apache License 2.0, described below.

**Comment by phst** [comment]
I've updated the PR accordingly.

**Comment by snarfed** [comment]
thank you! merging.

**Pull request merged**
